### ISSUE TITLE
Filters vs query params for endpoints

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-api#108]
In working with the API we have noticed that some endpoints use filters while others use ~~OPTIONS~~query params.  I think if we could work towards adding options for all endpoints that would give us a performance boost (at least on the client side)...every little bit helps.

Thoughts @AllenBW @gtanzillo?

/cc @Loicavenel @jonnyfiveiq @Fryguy @ohadlevy @bascar 

EDIT by @Fryguy: Changed the OPTIONS to query params to make this clearer.

**Comment by chriskacerguis** [comment]
Related to this https://github.com/ManageIQ/manageiq-api/issues/96

**Comment by Fryguy** [comment]
Not sure I understand where OPTIONS and filters overlap.  The purpose of OPTIONS is to give metadata about an endpoint in general, such as what are all of the possible attributes.  filters are a run-time thing where you say you want or don't want particular values.  While I don't disagree that OPTIONS for all endpoints would be useful, I don't understand the comparison with filters.

**Comment by chalettu** [comment]
I think @chriskacerguis you maybe getting confused with the http verb "options" vs the request format differences that we sometimes call options vs filters in a "get" request.  I think @AllenBW you have dealt with filters more a bit lately so chime in with an example of what Chris meant.

**Comment by AllenBW** [comment]
`http://localhost:3001/api/event_streams?expand=resources&filter[]=target_id%3D10000000002102&filter[]=target_type%3DVmOrTemplate&filter[]=timestamp%3E2017-10-2`

vs

`http://localhost:3001/api/vms/10000000002102/metric_rollups/?capture_interval=hourly&expand=resources&start_date=2017-10-9`

The former requires more work to formulate a call where as the latter  requires less

**Comment by Fryguy** [comment]
Does this make the API slow or just somewhat unwieldy?  I ask because this was linked to #96

**Comment by Fryguy** [comment]
Ah, just so we can agree on terminology so as not to confuse ourselves, I think we should use:

filters:
`http://localhost:3001/api/event_streams?expand=resources&filter[]=target_id%3D10000000002102&filter[]=target_type%3DVmOrTemplate&filter[]=timestamp%3E2017-10-2`

query params:
`http://localhost:3001/api/vms/10000000002102/metric_rollups/?capture_interval=hourly&expand=resources&start_date=2017-10-9`

Thoughts on terminology?

**Comment by chriskacerguis** [comment]
@Fryguy I would agree that is the correct terminology (query params vs. options).  Per @AllenBW 

> The former requires more work to formulate a call where as the latter requires less

So, it requires less "processing" so it's faster (maybe marginally, but something is better than nothing)

**Comment by AllenBW** [comment]
OOOOOO query params, love it @Fryguy 🙇‍♀️

**Comment by imtayadeway** [comment]
I'm leaning towards 👎 on this. To me, the filter is just another query param, it's just one that takes multiple values. What's more, this is the standard Rails Way to handle this scenario. Is there a plugin or similar in angular that could help make those calls easier to formulate?

The problem I foresee is that this could easily become a slippery slope. If we start adding separate params for everything that can be filtered, the scope of that could be enormous.

What's more, the filter is already more powerful in that it accepts things like comparison operators, etc..

Every extra query param we add to every API call also has to be documented, whereas the filter is already well documented.

> So, it requires less "processing" so it's faster (maybe marginally, but something is better than nothing)

I am also skeptical about this, since "less processing" does not always mean "faster". If you can provide some benchmarks, that may be more convincing. But I would strongly suspect if there was any difference it would be insignificant.

**Comment by Fryguy** [comment]
@AllenBW Could you give an example of how you would write the event_streams one with query params?  I'm inclined to agree with you in that there shouldn't be 2 different ways to pass parameters, but I'm curious which is preferable.

**Comment by chrisarcand** [comment]
> The problem I foresee is that this could easily become a slippery slope. If we start adding separate params for everything that can be filtered, the scope of that could be enormous.

I agree.

There are three usual ways to send arrays on the querystring that are used:

* `?numbers[]=1&numbers[]=2&numbers[]=3`
* `?numbers=1&numbers=2&numbers=3`
* `?numbers=1,2,3`

The reason filters are implemented as they are is because that's the standard Rails (and more importantly, Rack) convention established for passing arrays on the querystring:

```ruby
data = { numbers: [1,2,3] }
CGI.unescape data.to_query
# => "numbers[]=1&numbers[]=2&numbers[]=3"
```

I know that PHP and other communities follow this convention as well.

The metrics rollups API, sadly, is just a special snowflake that shouldn't have been implemented as it was as it basically circumvents the way we do it everywhere else.

Given this, I'm 👎  as well and don't see why we'd want to change it. I'm skeptical of any performance boost one would get from not having to just add `filters[]=` in a function that parses this for you. I would of course welcome any provided benchmarks proving the speed improvement though - in which case I would recommend option \#3 above as it's just as clean as far as the semantics of the API go while still avoiding the constant `filters[]=` that you dislike (and I've seen it used with great success in other APIs before).

**Comment by Fryguy** [comment]
I have a question on building the query string.  I hope you're not building them manually via string manipulation.  It's much better to use a library that does it for you...something like https://www.npmjs.com/package/query-string (which supports arrays in this syntax).

**Comment by imtayadeway** [comment]
I'm closing this as there seems to be a consensus here, but feel free to continue discussion or reopen as necessary.
