### ISSUE TITLE
If a resource doesn’t come in as hash or `{}` return bad request error

### ISSUE THREAD

**Issue by MelsHyrule** [ManageIQ/manageiq-api#1123]
If a resource doesn’t come in as hash or `{}` return bad request error. Current error message is misleading. (See image for reference where we passed in `"resources": "melody"`).

<img width="829" alt="Screen Shot 2022-01-26 at 2 05 08 PM" src="https://user-images.githubusercontent.com/29209973/151250822-5b335aa5-976c-4312-8ad3-a9114eae860b.png">

@miq-bot add-label bug
@miq-bot add-label enhancement
@miq-bot assign @MelsHyrule
@miq-bot assign @Fryguy

**Comment by Fryguy** [comment]
I think this is actually because the method you created didn't return the expected thing.  That is, I recall you created 

```
def add_host_resource(type, id, data)
  p type, id, data
end
```

as a test to see if your method was called.  However, the caller of add_host_resource is expecting a Hash to be returned.  I think we should still capture and hopefully present it nicer for developers, but I don't think this will ever get to end users.

**Comment by kbrock** [comment]
I think punt on this bug.
requiring that `def action_resource` returns an action hash (or an object, or array of objects) seems good to me.

**Comment by Fryguy** [comment]
Yeah this was more of a development bug, which won't land in production.
