### ISSUE TITLE
n+1 query when requesting services

### ISSUE THREAD

**Issue by imtayadeway** [ManageIQ/manageiq-api#146]
When I:

```http
GET http://localhost:3000/api/services?expand=resources&limit=20
```
I see that we have an n+1 problem:

#### The +1:
```
D, [2017-10-25T15:02:26.932359 #22628] DEBUG -- :   Service Load (0.3ms)  SELECT  "services".* FROM "services" LIMIT $1 OFFSET $2  [["LIMIT", 20], ["OFFSET", 0]]
```

#### For every n services:
```
D, [2017-10-25T15:02:26.996742 #22628] DEBUG -- :   Service Inst Including Associations (64.1ms - 20rows)
D, [2017-10-25T15:02:29.779592 #22628] DEBUG -- :   ServiceTemplate Load (0.2ms)  SELECT  "service_templates".* FROM "service_templates" WHERE "service_templates"."id" = $1 LIMIT $2  [["id", 10000000000005], ["LIMIT", 1]]
D, [2017-10-25T15:02:29.811939 #22628] DEBUG -- :   ServiceTemplate Inst Including Associations (32.1ms - 1rows)
D, [2017-10-25T15:02:29.814565 #22628] DEBUG -- :   ResourceAction Load (0.5ms)  SELECT  "resource_actions".* FROM "resource_actions" WHERE "resource_actions"."resource_id" = $1 AND "resource_actions"."resource_type" = $2 AND "resource_actions"."action" = $3 LIMIT $4  [["resource_id", 10000000000005], ["resource_type", "ServiceTemplate"], ["action", "Reconfigure"], ["LIMIT", 1]]
D, [2017-10-25T15:02:29.814762 #22628] DEBUG -- :   ResourceAction Inst Including Associations (0.0ms - 0rows)
D, [2017-10-25T15:02:29.817743 #22628] DEBUG -- :   CustomButton Load (0.2ms)  SELECT "custom_buttons".* FROM "custom_buttons" WHERE "custom_buttons"."applies_to_class" = $1 AND "custom_buttons"."applies_to_id" IS NULL  [["applies_to_class", "Service"]]
D, [2017-10-25T15:02:29.817925 #22628] DEBUG -- :   CustomButton Inst Including Associations (0.0ms - 0rows)
D, [2017-10-25T15:02:29.818388 #22628] DEBUG -- :   CustomButton Load (0.1ms)  SELECT "custom_buttons".* FROM "custom_buttons" WHERE "custom_buttons"."applies_to_class" = $1 AND "custom_buttons"."applies_to_id" = $2  [["applies_to_class", "ServiceTemplate"], ["applies_to_id", 10000000000005]]
D, [2017-10-25T15:02:29.818559 #22628] DEBUG -- :   CustomButton Inst Including Associations (0.0ms - 0rows)
D, [2017-10-25T15:02:29.819506 #22628] DEBUG -- :   CACHE (0.0ms)  SELECT "custom_buttons".* FROM "custom_buttons" WHERE "custom_buttons"."applies_to_class" = $1 AND "custom_buttons"."applies_to_id" IS NULL  [["applies_to_class", "Service"]]
D, [2017-10-25T15:02:29.819644 #22628] DEBUG -- :   CustomButton Inst Including Associations (0.0ms - 0rows)
D, [2017-10-25T15:02:29.821337 #22628] DEBUG -- :   CustomButtonSet Load (0.4ms)  SELECT "miq_sets".* FROM "miq_sets" WHERE "miq_sets"."set_type" IN ('CustomButtonSet') AND "miq_sets"."owner_id" = $1 AND "miq_sets"."owner_type" = $2  [["owner_id", 10000000000005], ["owner_type", "ServiceTemplate"]]
D, [2017-10-25T15:02:29.821522 #22628] DEBUG -- :   CustomButtonSet Inst Including Associations (0.0ms - 0rows)
```

That's 6 round trips to the database for every service we render back. This is almost certainly the one of the root causes of any slow query times reported against the services API

**Comment by abellotti** [comment]
Nice start on the analysis !!  Thanks @imtayadeway 

One thing to look at is how we fetch the additional attributes being asked for in the renderer, maybe we can pre-fetch what's being asked for in a single trip to the DB. I think the reporting engine does that for performance.  /cc @kbrock our performance guru would have some wise advice for us !!

**Comment by imtayadeway** [comment]
@abellotti you'll notice that in trying to find the simplest reproduction case I'm not requesting any additional attributes above:

```http
GET http://localhost:3000/api/services?expand=resources&limit=20
```

**Comment by abellotti** [comment]
Ahh ok, hopefully easier to isolate then.

For the SUI queries, they do ask for additional attributes, would be a different optimization then.  Thanks.

**Comment by chriskacerguis** [comment]
Perhaps just start adding a single attribute, optimize / troubleshoot it, then add another, (wash, rinse, repeat)?

**Comment by imtayadeway** [comment]
@abellotti @chriskacerguis regardless of what is going on with additional attributes, *every single query* is suffering from the problem as stated above. Let's try to fix this first, then examine what happens with more complex queries next.

**Comment by abellotti** [comment]
@imtayadeway can you look at the queries above without the expand=resources ?

From the queries being made I'm thinking it's the custom actions we need to interrogate for each each service as we populate the actions for each service.

**Comment by chrisarcand** [comment]
@imtayadeway and I did some spelunking and found two main causes of this issue, one of which is on the API to fix. The issue lies in the rendering code in the base controller. For every resource requested, the following is called:

https://github.com/ManageIQ/manageiq-api/blob/42813a23b65b485609033cbaa8d65041549b2e6b/app/controllers/api/base_controller/renderer.rb#L70-L87

### expand_actions (validate methods)

The call to `expand_actions` loads n+1 `service_templates` and `resource_actions` for every resource, because of the following:

https://github.com/ManageIQ/manageiq-api/blob/42813a23b65b485609033cbaa8d65041549b2e6b/app/controllers/api/base_controller/renderer.rb#L469-L475

That gets called here:

https://github.com/ManageIQ/manageiq-api/blob/42813a23b65b485609033cbaa8d65041549b2e6b/app/controllers/api/base_controller/renderer.rb#L444

So for every resource action on the collection, it calls a subsequent `validate_` method that might load something. For example, the `reconfigure` action on services has a `validate_action` option, thus `Service#validate_reconfigure` is called which loads a service template, etc. It's the responsibility of the API to try and fix this (although it might not be trivial).

### expand_resource_custom_actions (custom button implementation)

The call to `expand_resource_custom_actions` is bad because of multiple n+1s in the implementation of custom buttons. The issues can be found with the raw array appending and whatnot in https://github.com/ManageIQ/manageiq/blob/34433eeb70369dbcd44431781eb82c71b7b8bd88/app/models/mixins/custom_actions_mixin.rb

The implementation just needs to be more performant, and that's out of scope of the API unfortunately. If that can't be improved, I don't know if there's much we can do.

cc/ @gtanzillo

**Comment by imtayadeway** [comment]
From https://github.com/ManageIQ/manageiq-api/issues/146#issuecomment-341564249: 

> The call to expand_resource_custom_actions is bad because of multiple n+1s in the implementation of custom buttons. The issues can be found with the raw array appending and whatnot in https://github.com/ManageIQ/manageiq/blob/34433eeb70369dbcd44431781eb82c71b7b8bd88/app/models/mixins/custom_actions_mixin.rb

> The implementation just needs to be more performant, and that's out of scope of the API unfortunately. If that can't be improved, I don't know if there's much we can do.

/cc @d-m-u @gmcculloug

**Comment by Fryguy** [comment]
For CustomButton and CustomButtonSet, I'm not sure there much we can do about it tactically.  CustomerButtonSet is built using MiqSet, which internally uses the relationships table.  The way that table works, it's not possible to formulate a single query to get *all* of the sets and their children in a single query.

What *can* be done is typically to preload every service with their service_template and the custom button set object using `.includes`, and then just live with the N+1 for the relationships themselves.  If things are paged so we're not showing too much on a page at once, then typically this isn't a problem in practice.

**Comment by Fryguy** [comment]
Oh wait, WAT?  why would we validate any model on a GET request?

**Comment by chrisarcand** [comment]
@Fryguy and I worked on this tonight and came up with the following quickfix for the Euwe release: https://gist.github.com/Fryguy/7ebaf7e89490e00a0de564af3c5970b5

The result is a few large queries instead of the n+1 described, yielding a ~6x faster request. That is, an awful 30 second request with hundreds of services would now take around 5 seconds. A different 3.5s request now completed in .6s. 

We'll need to generalize and make this better for the addition of other things that have custom buttons for Gaprindashvili and onward. Basically the API needs preloading, and with the generic way we do everything it'll need to be generalized and smart about how to know what things it needs to preload (similar to reporting).

**Comment by Fryguy** [comment]
Made an EUWE PR here: https://github.com/ManageIQ/manageiq/pull/16426

I'll have to forward port for other versions, but wanted to get the PR out there.  Yes, it's a dirty dirty HACK and I don't care. 😝

**Comment by Fryguy** [comment]
Still working on this...turns out custom buttons are way worse, performance-wise on master/gaprindashvili.

**Comment by JPrause** [comment]
@abellotti is this still a valid issue? If yes, please remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
