### ISSUE TITLE
Unable to login with a newly created user

### ISSUE THREAD

**Issue by mzazrivec** [ManageIQ/manageiq-api#366]
How to reproduce:
1. In classic UI, create a new role, new group and a new user
2. try to login into the UI with the new user

You'll see the login fails.

During login, the following request is sent to API:
```
I, [2018-04-24T17:23:31.655840 #31920]  INFO -- : Started GET "/api/auth?requester_type=ui" for ::1 at 2018-04-24 17:23:31 +0200
I, [2018-04-24T17:23:31.748765 #31920]  INFO -- : Processing by Api::AuthController#show as JSON
I, [2018-04-24T17:23:31.749126 #31920]  INFO -- :   Parameters: {"requester_type"=>"ui"}
I, [2018-04-24T17:23:31.841456 #31920]  INFO -- : Filter chain halted as :require_api_user_or_token rendered or redirected
I, [2018-04-24T17:23:31.841585 #31920]  INFO -- : Completed 401 Unauthorized in 92ms (ActiveRecord: 10.2ms)
```

The json that comes back:
```
{"error":{"kind":"unauthorized","message":"Invalid User user01 specified, User's Group is missing","klass":"Api::AuthenticationError"}}
```

Inretestingly, logging in with `admin` user works fine.

**Comment by imtayadeway** [comment]
@mzazrivec I know that conversations about this issue have occurred variously on gitter etc.. - can you provide a few details here to help consolidate what we know;

1. What's the expected behavior?
1. Was there a time when the API performed the expected behavior, and
1. If so, can you identify a revision/release when the product did the right thing?

If you can also clarify the relationships between your user/role/groups in setup steps above?

I don't think I have a complete picture of what is going on - I think it was speculated on gitter that the reason it fails is because the user doesn't yet have a current group. I'm convinced this isn't the issue - we have had tests around this case which haven't changed in a long time - certainly predating the change in #359 .

Thanks!

**Comment by himdel** [comment]
[WIP answer, still looking for some details...]

@imtayadeway @mzazrivec is on PTO, I'll try to provide the details...


> 1. What's the expected behavior?

Ideally this should behave identically to the Rails login (TODO look up how that works).

Practically, the login just needs to not fail and needs to pick any group from `user.miq_groups` to be the `current_group`.

(In theory we could fail with a list of possible groups instead of picking one, but that potentially leaks info about user's group membership *and* would require extra UI.)


> 2. Was there a time when the API performed the expected behavior, and

Before https://github.com/ManageIQ/manageiq-ui-classic/pull/1752 this was a non-issue for non-LDAP users - only those could be a member of multiple groups. (TODO find out if it worked for LDAP)

Before https://github.com/ManageIQ/manageiq-api/pull/359, the exception did not fail the API login.


> 3. If so, can you identify a revision/release when the product did the right thing?

Before https://github.com/ManageIQ/manageiq-api/pull/359, the exception did not fail the API login.

The API never used to assign to `current_group` as far as I'm aware.

**Comment by himdel** [comment]
@mzazrivec , @imtayadeway Given that Rails login doesn't work without `current_group` either after all, and that creating users via the API (almost) works too, should we consider it an UI bug instead, and close this issue?

Meaning https://github.com/ManageIQ/manageiq-ui-classic/pull/3894 (or a similar PR) would become the fix for this.

**Comment by himdel** [comment]
@miq-bot close_issue

This was resolved by fixing how new users get created - https://github.com/ManageIQ/manageiq-ui-classic/pull/3917
