### ISSUE TITLE
[RFE]Standardize api methods available for all resources

### ISSUE THREAD

**Issue by lodgenbd** [ManageIQ/manageiq-api#653]
After getting involved with various code for a few months, I've found that there is no standard from what I can tell related to what methods are available for resources. Some resources have tagging available, some don't, but that's only because the code doesn't exist. Some resources have api methods available to access them, some don't, but, again, that's only because the code doesn't exist. I'd like to request that we (and I will help with pull requests) standardize what's available for method calls to resources. If a resource is available to be called, let's add the code for it. For example, my issue #641 where network_ports aren't available. Why not? It's available, it should be in the API, right?  I'm having trouble understanding why some are written and others aren't. Maybe someone can help me out, and maybe it's just because the code hasn't been written? But someone took the time to add others, why did we leave out some resources?

**Comment by martinpovolny** [comment]
> I'm having trouble understanding why some are written and others aren't

In most cases the answer is going to be: "Because noone wrote it yet."

@lodgenbd : please, if you have a more concrete requirement, create a more specific issue. Such as an issue listing all the collections that should have tagging but do not. I'll happily work on those.

This issue is like if you wrote "make the API better" or "complete the API" ;-)

Thx!

**Comment by mfeifer** [comment]
@lodgenbd can you please provide list of what you see as missing so that we can take action on it?

**Comment by h-kataria** [comment]
Closing due to lack of feedback
