### ISSUE TITLE
API requests with expand=resources can result in huge response sizes depending on the requested attributes

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/manageiq-api#866]
### Request an attribute from an association
```
# curl "https://user:password@example.com/api/vms?expand=resources&attributes=hardware.cpu_sockets" | wc -c
2809002
^^^ Huge response
```

### Add name attribute to prior request
```
# curl "https://user:password@example.com/api/vms?expand=resources&attributes=hardware.cpu_sockets,name" | wc -c
102005
^^^ Much smaller response
```

### Request an attribute from a virtual column/delegate
```
# curl "https://user:password@example.com/api/vms?expand=resources&attributes=num_cpu" | wc -c
2798304
^^^ Huge response
```

### Add name attribute to prior request
```
# curl "https://user:password@example.com/api/vms?expand=resources&attributes=num_cpu,name" | wc -c
91307
^^^ Much smaller response
```

**Comment by Fryguy** [comment]
Seems this is somewhat intentional behavior.  So, by default, `expand=resources` will add all physical columns to the resources, but _not_ virtual columns.  The expectation is that when you want to "add" a virtual column or a column via a relationship, you just tack on `attributes=<vcol>`.  However, if you pass `attributes=<pcol>` the expectation is that you only want those specific columns.  As such, if you want to limit the response you need to add in at least one physical column.  Ideally, we could change this such that if _anything_ is specified in the attributes it only returns that, but then we would break compatibility for the "add a virtual column" case (which is kind of documented here - https://www.manageiq.org/docs/reference/latest/api/overview/query.html#virtual-attributes-and-relationships )

There is an undocumented combination that we might be able to leverage however.  If one does _not_ pass `expand=resources`, but passes `attributes`, we effectively ignore attributes and only return hrefs.  This case can be changed to honor those attributes and return only those values.  Since we are only adding to the response and not taking anything away, we are not breaking compatbility.

**Comment by kbrock** [comment]
this kinda reminds me of active record. There is no way to use `select()` to tack on an attribute. you need to state all the ones you want or none at all.

It looks like here we have defined "if you `select(vcol)` then it is tack on behavior and if you `select(pcol)` then it is replace"
I do not think this is a good solution because it forces you to know whether a column is a vcol or a pcol.

If we want the user to treat the 2 columns different, then our documentation should state whether it is a virtual or a physical column.

Heh. And what happens when we convert a virtual column to a delegated physical column. Probably stays as a vcol but...
