### ISSUE TITLE
Add endpoint to revoke user sessions

### ISSUE THREAD

**Issue by jvlcek** [ManageIQ/manageiq-api#884]
This is a sub-issue of issue **_Ability to track and revoke sessions_** [#20378](https://github.com/ManageIQ/manageiq/issues/20378)

**Brief:**

A new endpoint needs to be added to allow a user sessions to be revoked

**Details:**

Introduce revoke session backend support and an api revoke session endpoint.

A user should be able to revoke their own sessions. A super-admin should be able to revoke anybody's sessions.

Might consider supporting `GET /api/revoke/user_session/:id`, if it is thought other resources could be added to revoke in the future.
If not might consider using `GET /api/revoke_user_session/:id `

Need to confirm that MCM needs an API GET call to end user sessions on other clients. POST might be more appropriate to this functionality;

Should perhaps consider

```
POST /api/revoke_session
{
  "userid" : "testuser", # default to current user, but support any user for the admin to use
  "type" : { "all" } # default to all
}

```

Parameterized support by type ("api", "ui", "ws", etc) needs to be supported with the default to "all". This work will be done as a follow up and tracked in Issue: **Parameterize endpoint to revoke user sessions by type** [#885](https://github.com/ManageIQ/manageiq-api/issues/885)

**Comment by abellotti** [comment]
Thanks for writing this @jvlcek, I kind of also prefer the POST since we're doing/changing something in the environment.

Here's what I'm thinking:

Revoking all session types for the authenticated user, no need to send _userid_ or _session_types_ since the userid is the authenticated user for the API call.

```
POST /api/revoke
```

Revoking one or more _session_types_ for the authenticated user:

```
POST /api/revoke
{
  "session_types" : ["ui", "api"]
}
```

Omitting _session_types_ is essentially an "all".

For an administrative account to deleting sessions for a user, with optional _session_types_:

```
POST /api/revoke
{
  "userid" : "any_user"
  "session_types" : ["ui"]
}
```
