### ISSUE TITLE
Trying to edit a Zone's authentication(s) crashes with AssociationTypeMismatch

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-api#898]
When I try this request:
```js
# POST /api/zones/X
{
  "action": "edit",
  "resource": {
    "authentications": [{ 
      "userid": "foo",
      "password": "bar", 
    }]
  }
}
```

It fails with:
```
[ActiveRecord::AssociationTypeMismatch] Authentication(#70163535308460) expected, got {"userid"=>"foo", "password"=>"bar"} which is an instance of Hash(#13895400).
```

I guess *The Right Way&trade;* would be to send three requests instead. One to check if there are any authentications, one to update the authentication and one to update the zone. Which might raise transactional concerns, because AFAIK there is no rollback support for chained API requests and I'm not sure if we want to compensate this feature on the frontend.

Anyway, the authentications is a special case in the `Zone` model as there's either zero or only one assinged. I am pretty sure I can fix this, but I have way too many ideas of how and I'm not entirely sure which one to choose.

Related issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/6917

@gtanzillo @abellotti @Fryguy 
@miq-bot add_label question

**Comment by skateman** [comment]
@miq-bot assign @gtanzillo

**Comment by NickLaMuro** [comment]
@skateman So I looked into this by literally writing a test to replicate the failure:

```diff
diff --git a/app/controllers/api/base_controller/generic.rb b/app/controllers/api/base_controller/generic.rb
index 6b943e8f..228c4f07 100644
--- a/app/controllers/api/base_controller/generic.rb
+++ b/app/controllers/api/base_controller/generic.rb
@@ -50,6 +50,9 @@ module Api
       def edit_resource(type, id, data)
         klass = collection_class(type)
         resource = resource_search(id, type, klass)
+        puts
+        puts data.except(*ID_ATTRS)
+        puts
         resource.update!(data.except(*ID_ATTRS))
         resource
       end
diff --git a/spec/requests/zones_spec.rb b/spec/requests/zones_spec.rb
index 3e955c81..40db8098 100644
--- a/spec/requests/zones_spec.rb
+++ b/spec/requests/zones_spec.rb
@@ -25,6 +25,22 @@ RSpec.describe "Zones" do
   end
 
   context "edit", :edit do
+    it "can update zone authentications" do
+      api_basic_authorize action_identifier(:zones, :edit)
+
+      zone   = FactoryBot.create(:zone, :description => "Current Zone description")
+      params = gen_request(:edit, "authentications" => [{"userid" => "foo", "password" => "bar"}])
+
+      post api_zone_url(nil, zone), :params => params
+
+      response_data = JSON.parse(response.body)
+
+      puts
+      puts response_data["error"]["message"]
+      puts response_data["error"]["backtrace"].lines[0..30]
+      puts
+    end
+
     it "will fail if you try to edit invalid fields" do
       api_basic_authorize action_identifier(:zones, :edit)
 
```

However, what I learned was that basically what is happening is that we are trying to pass:

```ruby
{"authentications"=>[{"userid"=>"foo", "password"=>"bar"}]}
```

to the `.update` of `#edit_resource`:

```ruby
def edit_resource(type, id, data)
  klass = collection_class(type)
  resource = resource_search(id, type, klass)
  resource.update!(data.except(*ID_ATTRS))
  resource
end
```

which I don't think is valid.

You "might" be able to do it if you pass IDs, but I haven't found anything on the internet to suggest this is something you can do via `ActiveRecord::Base#update!`.

cc @gtanzillo

**Comment by skateman** [comment]
@NickLaMuro we have this sorted out for [providers](https://github.com/ManageIQ/manageiq/blob/master/app/models/ext_management_system.rb#L62), so I guess we could do something similar? But I think this would need a more generic and global solution as I have this feeling that we will hit into the same wall for any new API endpoint. cc @agrare @Fryguy 

Passing IDs is not an option, that would need multiple queries and if something goes wrong between them, we would need to be able to deal with it on the frontend. BUT doing any kind of transaction recovery in the frontend code is just a no go, even writing down the idea feels wrong :sweat_smile:

**Comment by NickLaMuro** [comment]
@skateman I guess what I was getting at is this was advertised to me as a `bug`, and it is just not that, it is an enhancement.

**Comment by NickLaMuro** [comment]
So I had a PM with @gtanzillo regarding what our options were, and I figured I should share it here.

* * *

### Background

We previously had this line in the old controller:

https://github.com/ManageIQ/manageiq-ui-classic/blob/92cc572b/app/controllers/ops_controller/settings/zones.rb#L116

Which called this method on Zone, which is part of authentication mixin:

https://github.com/ManageIQ/manageiq/blob/717f2e4f9b6c7ad626a4145905d41f9ba830afb3/app/models/mixins/authentication_mixin.rb#L174-L247

So this is how the "bug" from above was allowed to work with the previous controller, andnone of this was standard Rails (hich is really what I was trying to point out with my first comment).  Further more, there is a lot of logic in those two methods doing that is doing data processing/munging that isn't obvious at first glance or standard for other controllers.


### Possible solutions

* Make a custom update action for the ZoneController, and allow that to do specific items for itself
  - This is the quick solution, but basically assumes custom documentation and coding for this particular endpoint, and I would argue this opens the gates for more of these types of "quick and dirty" solutions in the future
  - The result is we are basically taking all of the deleted code [from the controller in the UI](https://github.com/ManageIQ/manageiq-ui-classic/pull/7331/files#diff-46d9c2a2602cc981686abc11859bed16) and slapping it back into the API
* Do a "middle ground" solution of `resource.respond_to?(:api_update!) ? resource.api_update!(args) : resource.api_update!(args)`
  - Basically we add a "assumed interface" on models in core called `.api_update!`, that if available, would be used instead of just a default Rails `.update!`
  - A bit of a kludge, and a similar situation to the above, but should be less required for future updates to the codebase to add this elsewhere (however, doesn't really solve the documentation issues)
  - While we have done this in the API before, it is incredibly hidden where it is done, and isn't a well documented feature or pattern, so this would cause maintenance nightmares down the road.
* Make a generic solution for allowing updating nested attributes
  - _**MUCH**_ more work to do, and I would say it is akin to the complexity of [`API::BaseController::Render`](https://github.com/ManageIQ/manageiq-api/blob/master/app/controllers/api/base_controller/renderer.rb)
  - Arguably the least gross out of the three (or at least more maintainable)


### My two cents

(not that I really expect it to make a difference in the decision made)

I honestly don't want to do any of the above, because it sets a precedent of allowing the API clients to dictate the structure API, instead of the clients conforming to what is there.  Honestly, I think in this case we are at best just shuffling around technical debt instead and arguably adding to it by doing any of the above, and I am fearful we are going to be only perpetuating it by trying to "fix this fast".

**Comment by NickLaMuro** [comment]
📖 aside, let me know which option we are going with, and I can look at throwing together a POC.

**Comment by abellotti** [comment]
Trying to implement a  POST /api/zones/X approach for editing the authentications (a relationship) in the generic updates will probably bite us somewhere else.  I think it's best to expose them as a subcollection, this way we can better inject the necessary logic needed for this,

So introducing:

```
GET /api/zones/:id/authentications
```

```
POST /api/zones/:id/authentications   (and PUT or PATCH)
```

Where a PUT /api/zones/:id/authentications would handle the special  logic there, i.e. one and only one, etc.
And we're not introducing risk to the "rest".

**Comment by chessbyte** [comment]
@abellotti why is the code going through zones to get to authentications?  How are those 2 classes/tables related?

**Comment by abellotti** [comment]
OPTIONS /api/zones shows authentications as a relationship.  It's just an association via the include AuthenticationMixin in the zone model giving us $zone_object.authentications

**Comment by skateman** [comment]
> Trying to implement a POST /api/zones/X approach for editing the authentications (a relationship) in the generic updates will probably bite us somewhere else. I think it's best to expose them as a subcollection, this way we can better inject the necessary logic needed for this,
> 
> So introducing:
> 
> ```
> GET /api/zones/:id/authentications
> ```
> 
> ```
> POST /api/zones/:id/authentications   (and PUT or PATCH)
> ```
> 
> Where a POST /api/zones/:id/authentications would handle the special logic there, i.e. one and only one, etc.
> And we're not introducing risk to the "rest".

@abellotti from the frontend perspective it's not really a good idea to do 2 requests, because then we have to deal with transactions, i.e. cleaning up stuff if the second request fails. This kind of stuff should be sorted out in the backend as there is already an existing solution for that in ActiveRecord/postgresql.

**Comment by skateman** [comment]
> @abellotti why is the code going through zones to get to authentications? How are those 2 classes/tables related?

@chessbyte a zone has nested authentications for Windows credentials in that zone (I guess). Ideally I would need a single API endpoint that is able to deal with the related zone credentials sent as a nested attribute. We're doing something similar at the provider forms, but that's a little bit more advanced as they got more than one authentication attached to them and here we only got one.

**Comment by Fryguy** [comment]
I really don't understand zones having authentications...I think this might be a legacy thing that maybe we should remove... it was added by (ironically) @chessbyte in 2011 here:

```text
commit 21a7f7a043b5acc4bee5c728f8c7fb1d4340829a
Author: Oleg Barenboim <obarenbo@redhat.com>
Date:   Mon Oct 31 20:36:29 2011 +0000

    BugzID:13408

    Reinstated AuthenticationMixin for the Zone model (removed in case 13354).

    git-svn-id: http://miq-ubuntusub.manageiq.com/svn/svnrepos/Manageiq/trunk@31289 3c68ef56-dcc3-11dc-9475-a42b84ecc76f
```

**Comment by skateman** [comment]
@Fryguy I'm also okay with that :tada: we already removed the NTP servers

**Comment by Fryguy** [comment]
Seems it's used here? 

```
/Users/jfrey/dev/manageiq/app/models/vm/operations.rb:78:    if my_zone.nil? || my_zone_obj.auth_user_pwd(:windows_domain).nil?
/Users/jfrey/dev/manageiq/app/models/vm.rb:89:      cred = my_zone_obj.auth_user_pwd(:windows_domain)
/Users/jfrey/dev/manageiq/app/models/host.rb:864:      if !default_zone.nil? && default_zone.has_authentication_type?(:windows_domain)
/Users/jfrey/dev/manageiq/app/models/host.rb:865:        discover_options[:windows_domain] = [default_zone.authentication_userid(:windows_domain), default_zone.authentication_password_encrypted(:windows_domain)]
```

**Comment by Fryguy** [comment]
separately, btw, we've identified a bug in creating new auth records that you might be seeing here, and that @agrare is fixing in https://github.com/ManageIQ/manageiq/pull/20635

**Comment by Fryguy** [comment]
I would recommend against transaction management outside of the API.  For one, it's complicated and can do thing like a user leaving open-ended transactions (or worse DOS'ing the API by slamming it with open transactions and not closing them).  But, for another, the API interface is controlled by us so we can do everything at the API level...that is, the post method in the ApiZonesController could be aware that authentications in this structure are possible and then do the transactions there (most likely using the .assign_nested_authentication method).  

In providers we pushed that part of the auth interface deeper down into the models as part of the create_from_params (because providers can bring their own param structure) and the API just calls that, but technically that auth interface is part of the API itself.

**Comment by Fryguy** [comment]
Talked with @NickLaMuro and there already is a precedent for an authentications subcollection, so thinking that might be best.  Is it possible to create a parent record and include subcollection records in a single shot?  If so, that would seem to be the best of both worlds.

**Comment by agrare** [comment]
> @agrare are these code paths even possible anymore?

@Fryguy yes, both `Vm#running_processes` and `Host.discoverByIpRange` are currently called by the UI still

**Comment by NickLaMuro** [comment]
@agrare but would those be used by a `Zone`'s auth record?

(please note:  I only understand zones from a 500K foot standpoint, so I might be missing something obvious here)

**Comment by agrare** [comment]
@NickLaMuro yes, both of those examples look for an authentication record with type `:windows_domain` on the `Zone`

Check https://www.manageiq.org/docs/reference/latest/general_configuration/#creating-a-zone `#7` "Credentials - Windows Domain"

**Comment by chessbyte** [comment]
@agrare why would a windows authentication be on the zone?  does not make any sense to me (even though git shows that I added it in 2011).  Maybe because we had nowhere else to hang it off of?

**Comment by agrare** [comment]
Hey you asked if it was still used not why it was used :laughing: 

If I had to guess I'd say because all machines in a windows domain would share the same credentials so:
1. You don't want to be entering the same ones for every VM
2. Windows Domain would span providers so saving it at the EMS level isn't necessarily right (windows vms on vmware and rhv would both belong to the same domain)
3. You might have more than one windows domain to storing it at the application/region level might be too broad

So yeah I think "no where else to hang it off of" is the reason why it is on a zone

**Comment by Fryguy** [comment]
Yeah, I'm thinking "there was nowhere else to hang it off of", which isn't a great reason.  Strangely for individual VMs and hosts for SSH access we require a user to enter it on each individual machine.  I like the idea of not needing a user to enter credentials more than once, but perhaps there's a better pattern we can do here for both windows and ssh creds.  We do have the ability to enter arbitrary authentications for embedded ansible now, so maybe we can reuse some of that?

Even so, the feature exists, and it does require hanging a credential off of a zone, so seems we need to expose this regardless.

**Comment by chessbyte** [comment]
`Host.discoverByIpRange` does get the zone auth and sets it in `discover_options[:windows_domain]`.  However, it does not seem to be used in the discovery code.  So, we may be able to delete that one.

**Comment by agrare** [comment]
@chessbyte it looks like it is called from here: https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/mixins/actions/host_actions/discover.rb#L83 unless that is also dead code

**Comment by chessbyte** [comment]
@agrare I mean that `:windows_domain` is not used by Host discovery code.

**Comment by agrare** [comment]
Ah okay :+1:

**Comment by chessbyte** [comment]
`Vm#running_processes` _does_ use `:windows_domain` when it calls `WMIHelper.connectServer(ipaddr, *cred)`
