### ISSUE TITLE
Retrieving a list of available rbac tenant quotas

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-api#982]
When retrieving the list of tenant quotas for a given tenant, the UI calls the [`Tenant#get_quotas`](https://github.com/ManageIQ/manageiq/blob/master/app/models/tenant.rb#L137-L141) method which merges together the assigned quotas with all the other quotas that can be possibly assigned. When requesting quotas for a given tenant via the API, I can only access the assigned oned, but not the possibilities.

I am thinking about an `OPTIONS` request similarly to how we did it with the [snapshots](https://github.com/ManageIQ/manageiq-api/pull/943) but here we don't have a mixin, but the tenant quotas have a separate controller, while behaving as a subcollection.

@abellotti I think I need your help on how to tackle this

Parent issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/6866

**Comment by abellotti** [comment]
We can certainly provide this via `OPTIONS /api/tenants/X/quotas`, but since the information is general to all, and `OPTIONS /api/quotas`  (the real endpoint for TenantQuota) is not available since it is a subcollection only, we can provide this information with  `OPTION /api/tenants` in the data section returning "quota_definitions". (from TenantQuota.quota_definitions).
